server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie
      timeout: 10m

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://13.125.146.255:3306/app?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/app?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: goldentime
    password: 1234

  mail:
    host: smtp.gmail.com
    port: 587
    username: gtaemin254@gmail.com
    password: csly lxto vgxw iuhl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*/*.xml
  type-handlers-package: com.example.back.config.mybatis.handler
  type-aliases-package: com.example.back.domain;com.example.back.dto;