server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie
      timeout: 10m

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.209.5.120:3306/app?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://localhost:3306/app?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: goldentime
    password: 1234
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5MB
      max-file-size: 5MB
      max-request-size: 15MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: gtaemin254@gmail.com
    password: csly lxto vgxw iuhl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*/*.xml
  type-handlers-package: com.example.back.config.mybatis.handler
  type-aliases-package: com.example.back.domain;com.example.back.dto;