server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie
      timeout: 10m

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13.125.146.255/app?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: goldentime
    password: 1234
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml
  type-handlers-package: com.example.app.config.mybatis.handler
  type-aliases-package: com.example.app.domain;com.example.app.dto;